# -*- coding: utf-8 -*-
"""Sheets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wrfaZTup2vez7RwmME8l3iTyplpzx7FH
"""

!pip install -q gspread google-auth

import os

print(os.listdir())

import os

for root, dirs, files in os.walk('/content'):
    for file in files:
        if file.endswith('.json'):
            print(os.path.join(root, file))

import os
print(os.listdir('/content'))

import gspread
from google.oauth2.service_account import Credentials

SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]

creds = Credentials.from_service_account_file(
    "/content/bot-admisiones-123456.json",
    scopes=SCOPES
)

gc = gspread.authorize(creds)

print("Conexión exitosa")

sheet = gc.open("admisiones").sheet1

print(sheet.title)

sheet.append_row([
    "2026-06-15",
    "0999999999",
    "SI",
    "2026-06-15 09:00",
    "Prueba representante",
    "Prueba estudiante",
    "5",
    "Inicial 2",
    "prueba@correo.com",
    "Información",
    "Nuevo",
    "Registro automático desde Colab"
])

print("Fila guardada correctamente")

import requests

TOKEN = "EAAbIZAZCC9l7kBRn9vLOhdZCvp3v6jo7BNVKOfHVCGRmmL9lo1ZCCFvmIuFUc8abD0hVijQXVjyTkPMqTUfvlFVuwTsZATwRAVFXb7HWMZAmuGr7WrBOL9U5h9rGGiA7KcU0p9mAHLQuT88eiPXysB2EoZC4fWJSjPChAC3mDPMObkInPwfdSzAUtsBgOlXK8UCZA1iZBxQQxZAL9PPrZAWZAGzppi16jgsiwetcpZAwTt5mZAH0ps09PJIjV4VgBd11lJCUABAZCgGhaQ1ZAmPuhp3SsdGdw5G8"
PHONE_NUMBER_ID = "1165732796623545"

url = f"https://graph.facebook.com/v23.0/{PHONE_NUMBER_ID}/messages"

headers = {
    "Authorization": f"Bearer {TOKEN}",
    "Content-Type": "application/json"
}

data = {
    "messaging_product": "whatsapp",
    "to": "593993083025",
    "type": "text",
    "text": {
        "body": "Hola 👋. Esta es la primera prueba del Bot de Admisiones."
    }
}

response = requests.post(url, headers=headers, json=data)

print(response.status_code)
print(response.text)

!pip install -q flask pyngrok

from flask import Flask, request
from pyngrok import ngrok
import threading

app = Flask(__name__)

VERIFY_TOKEN = "ecomundo2026"

@app.route("/webhook", methods=["GET"])
def verify():
    mode = request.args.get("hub.mode")
    token = request.args.get("hub.verify_token")
    challenge = request.args.get("hub.challenge")

    if mode and token:
        if mode == "subscribe" and token == VERIFY_TOKEN:
            return challenge, 200

    return "Error de verificación", 403


@app.route("/webhook", methods=["POST"])
def webhook():
    data = request.get_json()

    print("Mensaje recibido:")
    print(data)

    return "OK", 200

def run():
    app.run(host="0.0.0.0", port=5000)

thread = threading.Thread(target=run)
thread.start()

from pyngrok import ngrok

ngrok.set_auth_token("2zyQVcYF8lcwwEWkcQujexCdGbG_7ZVwKi46QmmtGspqxqgHD")

public_url = ngrok.connect(5000)

print("Webhook URL:")
print(public_url)

import requests

r = requests.get(
    "https://f826-35-201-150-153.ngrok-free.app/webhook"
)

print(r.status_code)
print(r.text)

VERIFY_TOKEN = "ecomundo2026"

from pyngrok import ngrok
import os
import signal

# Cerrar todos los túneles de ngrok activos
ngrok.kill()

print("Túneles de ngrok cerrados")

public_url = ngrok.connect(5000)

print("Webhook URL:")
print(public_url)

!pip install -q flask pyngrok requests gspread google-auth

from flask import Flask, request
from pyngrok import ngrok
import threading

app = Flask(__name__)
VERIFY_TOKEN = "ecomundo2026"

@app.route("/webhook", methods=["GET"])
def verify():
    mode = request.args.get("hub.mode")
    token = request.args.get("hub.verify_token")
    challenge = request.args.get("hub.challenge")

    if mode == "subscribe" and token == VERIFY_TOKEN:
        return challenge, 200

    return "Error de verificación", 403


@app.route("/webhook", methods=["POST"])
def webhook():
    data = request.get_json()
    print("MENSAJE RECIBIDO:")
    print(data)
    return "OK", 200


def run():
    app.run(host="0.0.0.0", port=5000)

thread = threading.Thread(target=run)
thread.start()

ngrok.set_auth_token("2zyQVcYF8lcwwEWkcQujexCdGbG_7ZVwKi46QmmtGspqxqgHD")

public_url = ngrok.connect(5000)

print("Webhook URL:")
print(public_url)

import requests

r = requests.get("https://1986-35-201-150-153.ngrok-free.app/webhook")
print(r.status_code)
print(r.text)

import requests

payload = {
    "prueba": "hola desde prueba directa"
}

r = requests.post(
    "https://1986-35-201-150-153.ngrok-free.app/webhook",
    json=payload
)

print(r.status_code)
print(r.text)